services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alta-store-api
    ports: 
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-proot", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      CONNECTION_STRING: root:root@tcp(appDb:3306)/alta-store-api?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080